Lsp = {}

require("rc.configs.lsp.inlay_hints")
require("rc.configs.lsp.on_attach")
require("rc.configs.lsp.diagnostic")
require("rc.configs.lsp.util")

require("rc.configs.neoconf")
require("rc.configs.neodev")

require("rc.configs.lsp.ls.vuels")
-- require("rc.configs.lsp.ls.eslint")
require("rc.configs.lsp.ls.tsserver")
-- require("rc.configs.lsp.ls.volar")
require("rc.configs.lsp.ls.lua_ls")
-- require("rc.configs.lsp.ls.teal_ls")
-- require("rc.configs.lsp.ls.rust_analyzer")
-- require("rc.configs.lsp.ls.rls")
require("rc.configs.lsp.ls.solidity")
require("rc.configs.lsp.ls.jdtls")
require("rc.configs.lsp.ls.pyright")
-- require("rc.configs.lsp.ls.pylsp")
-- require("rc.configs.lsp.ls.jedi")
-- require("rc.configs.lsp.ls.pylyzer")
require("rc.configs.lsp.ls.jsonls")
require("rc.configs.lsp.ls.bashls")
require("rc.configs.lsp.ls.yamlls")
-- require("rc.configs.lsp.ls.taplo")
require("rc.configs.lsp.ls.dockerls")
require("rc.configs.lsp.ls.html")
require("rc.configs.lsp.ls.clangd")
require("rc.configs.lsp.ls.gopls")
require("rc.configs.lsp.ls.graphql")
